/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vuelouy.interfaz.common;

import vuelouy.dominio.Musica;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.Observable;
import java.util.Observer;
import java.util.Set;
import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.Timer;

/**
 *
 * @author Usuario
 */
public class MenuReproducirMusica extends javax.swing.JPanel implements Observer, ActionListener {

    private ComunicacionPaneles comunicacion;
    private Musica musica;
    private Timer timer;
    private int timepo;

    /**
     *
     */
    public MenuReproducirMusica() {
        initComponents();
    }

    /**
     *
     * @param p
     */
    public MenuReproducirMusica(ComunicacionPaneles p) {
        comunicacion = p;
        comunicacion.addObserver(this);
        initComponents();
        slVolumen.setValue(100);
        lblVolumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rvol4.png")));
        musica = new Musica();
        lstCanciones.setModel(getModelList());
        lstCanciones.setSelectedIndex(0);
    }

    private DefaultListModel<String> getModelList(){
        DefaultListModel<String> model = new DefaultListModel<>();
        Set<String> s = new LinkedHashSet<>(musica.getListaMusicas());
        Iterator<String> it = s.iterator();
        int position = 0;
        while (it.hasNext()){
            it.next();
            String nombre = musica.getListaMusicas().get(position).substring(17);
            model.addElement(nombre);
            position++;
        }
        return model;  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        btnPlay = new javax.swing.JButton();
        btnSig = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        slVolumen = new javax.swing.JSlider();
        lblVolumen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCanciones = new javax.swing.JList();
        btnVolver = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setEnabled(false);

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rplay.png"))); // NOI18N
        btnPlay.setBorder(null);
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.setPreferredSize(new java.awt.Dimension(64, 64));
        btnPlay.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/RplayP.png"))); // NOI18N
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPlayMouseReleased(evt);
            }
        });

        btnSig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rsig.png"))); // NOI18N
        btnSig.setBorder(null);
        btnSig.setBorderPainted(false);
        btnSig.setContentAreaFilled(false);
        btnSig.setPreferredSize(new java.awt.Dimension(64, 64));
        btnSig.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/RsigP.png"))); // NOI18N
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });

        btnAnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rant.png"))); // NOI18N
        btnAnt.setBorder(null);
        btnAnt.setBorderPainted(false);
        btnAnt.setContentAreaFilled(false);
        btnAnt.setPreferredSize(new java.awt.Dimension(64, 64));
        btnAnt.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/RantP.png"))); // NOI18N
        btnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntActionPerformed(evt);
            }
        });

        slVolumen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slVolumenStateChanged(evt);
            }
        });

        lblVolumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rvol4.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(btnAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSig, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(slVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSig, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(slVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addComponent(lblVolumen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lstCanciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lstCanciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstCanciones);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Volver.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setPreferredSize(new java.awt.Dimension(96, 96));
        btnVolver.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/VolverP.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        comunicacion.setBPanel(true);
        comunicacion.cambio("Entretenimiento");
    }//GEN-LAST:event_btnVolverActionPerformed

    private void slVolumenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slVolumenStateChanged
        int volumen = slVolumen.getValue();
        if (volumen == 0) {
            lblVolumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rvol1.png")));
        } else if (volumen <= 35) {
            lblVolumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rvol2.png")));
        } else if (volumen >= 70) {
            lblVolumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rvol3.png")));
        } else if (volumen == 100) {
            lblVolumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rvol4.png")));
        }
    }//GEN-LAST:event_slVolumenStateChanged

    private void btnPlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMousePressed
        if (musica.estaReproduciendo()) {
            btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/RstopP.png")));
            musica.parar();
            timer.stop();
            timepo = 0;
            progressBar.setValue(0);
        } else {
            btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/RplayP.png")));
            musica.reproducir();
            timer = new Timer(150, this);
            timer.start();
        }
    }//GEN-LAST:event_btnPlayMousePressed

    private void btnPlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseReleased
        if (musica.estaReproduciendo()) {
            btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rstop.png")));
        } else {
            btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rplay.png")));
        }
    }//GEN-LAST:event_btnPlayMouseReleased

    private void btnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntActionPerformed
        if (musica.estaReproduciendo()) {
            btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rstop.png")));
        } else {
            btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rplay.png")));
        }
        
        if (musica.estaReproduciendo()) {
            timer.stop();
            progressBar.setValue(0);
            timepo = 0;
        }
        musica.anterior();
        if (lstCanciones.getSelectedIndex() == 0) {
            lstCanciones.setSelectedIndex(lstCanciones.getModel().getSize()-1);
        } else {
            lstCanciones.setSelectedIndex(lstCanciones.getSelectedIndex()- 1);
        }
    }//GEN-LAST:event_btnAntActionPerformed

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
        if (musica.estaReproduciendo()) {
            btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rstop.png")));
        } else {
            btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rplay.png")));
        }
        
        if (musica.estaReproduciendo()) {
            timer.stop();
            progressBar.setValue(0);
        timepo = 0;
        }
        musica.siguiente();
        if (lstCanciones.getSelectedIndex() == lstCanciones.getModel().getSize()-1) {
            lstCanciones.setSelectedIndex(0);
        } else {
            lstCanciones.setSelectedIndex(lstCanciones.getSelectedIndex() + 1);
        }
    }//GEN-LAST:event_btnSigActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
            JFileChooser file=new JFileChooser();
            file.showSaveDialog(this);
            File archivo =file.getSelectedFile();
            if (archivo != null) {
            Path origenPath = FileSystems.getDefault().getPath(archivo.getParent());
            Path destinoPath = FileSystems.getDefault().getPath("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\VueloUY\\src\\vuelouy\\sonidos\\");
            File f;
            try{      
                f = new File(origenPath + "//" + archivo.getName());
                if(f.renameTo(new File(destinoPath + "//" + archivo.getName())))
                {
                    lstCanciones.setModel(this.getModelList());
                    lstCanciones.setSelectedIndex(0);
                }
            }
            catch(Exception e)
            {
                e.printStackTrace(System.out);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnSig;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVolumen;
    private javax.swing.JList lstCanciones;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JSlider slVolumen;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (comunicacion.getBPanel()) {
            this.setVisible(false);
            comunicacion.getVentanaInicioP().mostrarSubMenu(comunicacion.getPanel());
            
        }
    }
    private static final Logger LOG = getLogger(MenuReproducirMusica.class.getName());

    @Override
    public void actionPerformed(ActionEvent e) {
        if (timepo == 100) {
            timer.stop();
            timepo = 0;
            if (musica.estaReproduciendo()) {
                musica.parar();
                progressBar.setValue(0);
            }
            btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Rplay.png")));
        } else {
            timepo++;
            progressBar.setValue(timepo);
        }
    }

}
